{% set name = "sos" %}
{% set version = "0.25.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f5bedbf516567ed81e6f6cc4ca5130e404df708e5f2ba2430ab843c8fd1c10e

build:
  noarch: python
  number: 1
  entry_points:
    - sos=sos.__main__:main
    - sos-runner=sos.__main__:sosrunner
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - fasteners
    - jinja2
    - nbformat
    - networkx
    - pexpect
    - ptyprocess
    - psutil
    - pydot
    - pydotplus
    - pygments
    - python >={{ python_min }}
    - python-xxhash
    - pyyaml
    - pyzmq
    - setuptools
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - sos
    - sos.docker
    - sos.singularity
  commands:
    - sos --help
    - sos-runner --help

about:
  home: https://github.com/vatlab/SoS
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'Script of Scripts (SoS): an interactive, cross-platform, and cross-language workflow system for reproducible data analysis'
  doc_url: https://vatlab.github.io/sos-docs/


extra:
  recipe-maintainers:
    - danielnachun
    - BoPeng
    - gaow
    - jdblischak
