{% set name = "sos" %}
{% set version = "0.23.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01f4359c744702a2c8f0b2e305d630f1b4671bafdcc72581732b6d99fee5ff7d

build:
  noarch: python
  number: 0
  entry_points:
    - sos=sos.__main__:main
    - sos-runner=sos.__main__:sosrunner
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - fasteners
    - jinja2
    - nbformat
    - networkx
    - pexpect
    - ptyprocess
    - psutil
    - pydot
    - pydotplus
    - pygments
    - python >=3.6
    - python-xxhash
    - pyyaml
    - pyzmq
    - setuptools
    - tqdm

test:
  imports:
    - sos
    - sos.docker
    - sos.singularity
  commands:
    - sos --help
    - sos-runner --help

about:
  home: https://github.com/vatlab/SoS
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'Script of Scripts (SoS): an interactive, cross-platform, and cross-language workflow system for reproducible data analysis'
  doc_url: https://vatlab.github.io/sos-docs/


extra:
  recipe-maintainers:
    - BoPeng
    - gaow
    - jdblischak
