{% set name = "sos" %}
{% set version = "0.22.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff6da469e9662090f771782e05180b93b7236aff88d2c6d00a920de8d4acaab9

build:
  noarch: python
  number: 0
  entry_points:
    - sos=sos.__main__:main
    - sos-runner=sos.__main__:sosrunner
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - fasteners
    - jinja2
    - nbformat
    - networkx
    - pexpect
    - ptyprocess
    - psutil
    - pydot
    - pydotplus
    - pygments
    - python >=3.6
    - python-xxhash
    - pyyaml
    - pyzmq
    - setuptools
    - tqdm

test:
  imports:
    - sos
    - sos.docker
    - sos.singularity
  commands:
    - sos --help
    - sos-runner --help

about:
  home: https://github.com/vatlab/SoS
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'Script of Scripts (SoS): an interactive, cross-platform, and cross-language workflow system for reproducible data analysis'
  doc_url: https://vatlab.github.io/sos-docs/


extra:
  recipe-maintainers:
    - BoPeng
    - gaow
    - jdblischak
