schema_version: 1

context:
  version: 0.25.2

package:
  name: sos
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sos/sos-${{ version }}.tar.gz
  sha256: ac67926617f7dc0224940d0a33132895728a081c598c1e7460c584a846ef2e1c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  python:
    entry_points:
      - sos=sos.__main__:main
      - sos-runner=sos.__main__:sosrunner

requirements:
  host:
    - pip
    - python =${{ python_min }}
    - hatchling
    - setuptools
  run:
    - fasteners
    - jinja2
    - nbformat
    - networkx
    - packaging
    - pexpect
    - pillow
    - ptyprocess
    - psutil
    - pydot
    - pydotplus
    - pygments
    - python >=${{ python_min }}
    - python-xxhash
    - pyyaml
    - pyzmq
    - setuptools
    - tqdm

tests:
  - python:
      imports:
        - sos
        - sos.docker
        - sos.singularity
  - requirements:
      run:
        - python =${{ python_min }}
    script:
      - sos --help
      - sos-runner --help

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Script of Scripts (SoS): an interactive, cross-platform, and cross-language workflow system for reproducible data analysis"
  homepage: https://github.com/vatlab/SoS
  documentation: https://vatlab.github.io/sos-docs/

extra:
  recipe-maintainers:
    - danielnachun
    - BoPeng
    - gaow
    - jdblischak
